name: CI With Maven

on:
  push:
  pull_request:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Clonacion de Codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Build With Maven
        run: |
          mvn package

      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
			    -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
			    -Dsonar.host.url=https://sonarcloud.io \
			    -Dsonar.organization=luiscalquin \
			    -Dsonar.projectKey=luiscalquin_microservicio-java
